package com.udmtek.DBCoreGen.Comm;

public class DBCoreGenFormat {
	private static final String commentString="/***" + 
			"* @author julu1 <julu1 @ naver.com >" + 
			"* @version 0.1.0" +
			"* generated by DBCoreGen" +
			"*/";

	public static final String DAOHeader = "import java.util.Date;\r\n" + 
			"import javax.persistence.Column;\r\n" + 
			"import javax.persistence.Entity;\r\n" + 
			"import javax.persistence.Id;\r\n" + 
			"import javax.persistence.IdClass;\r\n" + 
			"import javax.persistence.Table;\r\n" + 
			"import javax.persistence.Temporal;\r\n" + 
			"import javax.persistence.TemporalType;\r\n" + 
			"import javax.persistence.Transient;\r\n" + 
			"\r\n" + 
			"import org.hibernate.annotations.CreationTimestamp;\r\n" + 
			"import com.udmtek.DBCore.DAOModel.EntityImpl;\r\n" + 
			"import com.udmtek.DBCore.DAOModel.EntityKeyImpl;\r\n" + 
			"\r\n" + 
			"import lombok.Getter;\r\n" + 
			"import lombok.Setter;\r\n" + 
			"import lombok.ToString;\r\n" + 
			"\r\n" + 
			"//update SQL 생성 시 빈칼럼은 제거한다.\r\n" + 
			"@org.hibernate.annotations.DynamicUpdate\r\n" + 
			"//insert SQL 생성 시 빈칼럼은 제거한다.\r\n" + 
			"@org.hibernate.annotations.DynamicInsert\r\n" + 
			"@Getter\r\n" + 
			"@Setter \r\n" + 
			"@ToString\r\n" + 
			"@Entity";
	
	public static final String DAOClassDefine="@Table(name=\"<TABLENAME>\")\r\n" + 
			"@IdClass(<CLASSNAME>.Key.class)\r\n" + 
			"public class <CLASSNAME> extends EntityImpl {";
	
	public static final String DAOColumnDefine="@Column(name=\"<COLUMNNAME>\")";
	
}
